### ISSUE TITLE
ESM Support

### ISSUE THREAD

**Issue by FC5570** [PteroPackages/PteroJS#19]
Currently this package does not support ESM. It would be great if this functionality is added. [gen-esm-wrapper](https://npmjs.com/gen-esm-wrapper) can be used to generate ESM bindings.

**Comment by devnote-dev** [comment]
Sounds like a good idea, I'm wondering if this can be done with the TypeScript config file so that new versions don't need to do extra building for releases. 🤔

**Comment by FC5570** [comment]
It does not need any extra config. You just have to add exports to your package.json.

I'm willing to contribute btw. Need this for a project.

**Comment by devnote-dev** [comment]
Feel free to open a PR, I'll be able to do some testing tomorrow. This should also hopefully add Deno support too.

**Comment by devnote-dev** [comment]
Added in #20, will come in the next release.
