### ISSUE TITLE
`app.allocations.fetchAvailable(1, true);` gives me "404: The requested resource could not be found on the server." - Uncaught PteroAPIError Error

### ISSUE THREAD

**Issue by BlaBlak2** [PteroPackages/PteroJS#30]
ERROR:
```
(node:20352) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
index.js:279
Uncaught PteroAPIError Error: 
- 404: The requested resource could not be found on the server.
    at handleError (file:///C:/Users/Admin/node_modules/@devnote-dev/pterojs/dist/index.js:1568:11)
    at <anonymous> (file:///C:/Users/Admin/node_modules/@devnote-dev/pterojs/dist/index.js:1517:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Process exited with code 1
```

CODE (pretty much the code in the example):
```
const { PteroApp } = require('@devnote-dev/pterojs');

const app = new PteroApp(
    'https://mc.abysl.dev/', // <-- this is the panel, the node is at http://mc.abysl.dev:8080/
    'REDACTED'
);

(async () => {
    const alloc = await app.allocations.fetchAvailable(1, true);
    const server = await app.servers.create({
        name: 'Welcome',
        user: 1,
        egg: 5,
        dockerImage: 'ghcr.io/pterodactyl/yolks:java_18',
        startup:
            'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar {{SERVER_JARFILE}}',
        environment: {
            MINECRAFT_VERSION: 'latest',
            SERVER_JARFILE: 'server.jar',
            DL_PATH: '',
            BUILD_NUMBER: 'latest'
        },
        limits: {
            cpu: 1000,
            memory: 8192,
            swap: 0,
            disk: 4096,
            io: 200
        },
        featureLimits: {
            allocations: 0,
            backups: 1,
            databases: 0,
        },
        allocation: {
            default: alloc.id,
        },
    });

    console.log(server);
})();
```

Anything obvious I'm missing? I'm not sure why it's not working, is there something I need to install on the server? When I try the wing/node, it says unauthorized, with use and application keys. When I try the panel, it says not found, for user and application keys.

EDIT: If I type a port directly instead of using allocation, I do get "422: The selected allocation.default is invalid.". If I understand correctly (although I am a little sleep deprived), this means it's a problem with getting the ports. Since the server can respond with that, but when I try to get an allocation, it says 404 - another edit: confirmed, this. I can't get the allocations. It returns 404. Is there another way to choose one maybe? Works perfecty if I use an id from 3000 to 3999 and add 1 to it

**Comment by devnote-dev** [comment]
The warning `NODE_TLS_REJECT_UNAUTHORIZED` is unrelated to the project but I'd advise fixing it as it might affect requests.

> ```
> const alloc = await app.allocations.fetchAvailable(1, true);
> ```

As per the docs for the [`fetchAvailable`](https://pteropackages.github.io/PteroJS/classes/NodeAllocationManager.html#fetchAvailable) method, the first argument is the ID of the target node, so the 404 means a node with that ID does not exist.
