### ISSUE TITLE
Spelling Mistake in PteroClient.

### ISSUE THREAD

**Issue by ALEXWARELLC** [PteroPackages/PteroJS#32]
![image](https://github.com/PteroPackages/PteroJS/assets/123724383/8fc350e0-1324-45b6-9303-602bca2901a9)

Attached above is an image exposing the spelling mistake made.

**Comment by yesBad** [comment]
> ![image](https://private-user-images.githubusercontent.com/123724383/341966699-8fc350e0-1324-45b6-9303-602bca2901a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDE2OTksIm5iZiI6MTcxOTQwMTM5OSwicGF0aCI6Ii8xMjM3MjQzODMvMzQxOTY2Njk5LThmYzM1MGUwLTEzMjQtNDViNi05MzAzLTYwMmJjYTI5MDFhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxMTI5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjY3NzNlY2U0YzY5MzU3MWI3MWU1NGU5MDE5ZmI2NTk0ZDMwOWE5YzViNzU1OTg4MWZlZTI0ZjZhNGIyNzNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JhqeJVTxG5rkikFwdQzgK81JtV7I0-_XQVRRPhKuDZQ)
> 
> Attached above is an image exposing the spelling mistake made.

Why not just make a pr..?

**Comment by ALEXWARELLC** [comment]
> > ![image](https://private-user-images.githubusercontent.com/123724383/341966699-8fc350e0-1324-45b6-9303-602bca2901a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDE2OTksIm5iZiI6MTcxOTQwMTM5OSwicGF0aCI6Ii8xMjM3MjQzODMvMzQxOTY2Njk5LThmYzM1MGUwLTEzMjQtNDViNi05MzAzLTYwMmJjYTI5MDFhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxMTI5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjY3NzNlY2U0YzY5MzU3MWI3MWU1NGU5MDE5ZmI2NTk0ZDMwOWE5YzViNzU1OTg4MWZlZTI0ZjZhNGIyNzNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JhqeJVTxG5rkikFwdQzgK81JtV7I0-_XQVRRPhKuDZQ)
> > Attached above is an image exposing the spelling mistake made.
> 
> Why not just make a pr..?

I wasn't exactly sure if this repository was being actively worked on + the issue could easily be fixed but I can make one now.
