### ISSUE TITLE
Websocket connection attempt results in 403

### ISSUE THREAD

**Issue by chelog** [PteroPackages/PteroJS#9]
Given code:
```ts
import { ClientServer, PteroClient } from '@devnote-dev/pterojs';

async function run() {
	const client = new PteroClient('https://mydomain.com', '-snip-', {
		ws: true,
	})

	client.on('debug', console.log)

	// I created PR to fix client.addSocketServer() thus using the hack
	client.ws.servers.push('d7d01832')
	client.on('serverOutput', (id, output) => {
		console.log({ id, output });
	})

	await client.connect()
}

run()
```

results in:
```
Error: Unexpected server response: 403
    at ClientRequest.<anonymous> (/path/to/myproject/node_modules/.pnpm/ws@8.5.0/node_modules/ws/lib/websocket.js:852:7)
    at ClientRequest.emit (node:events:526:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:618:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:482:22)
    at TLSSocket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
[ERROR] 19:11:15 Error: Unexpected server response: 403
```

Pterodactyl: 1.7.0 (latest)

**Comment by chelog** [comment]
I ran into similar issue on StackOverflow, however author doesn't seem to use this library:
https://stackoverflow.com/questions/70748325/403-forbidden-when-connecting-to-pterodactyl-websocket

**Comment by devnote-dev** [comment]
If I remember correctly, 403 can mean that the API key is invalid (using an application API key instead of a client API key), or the origin of the websocket request is not whitelisted. The latter is not under PteroJS' control, `cross_origin` in the Wings configuration needs to include your IP or "*" (allows all origins) for it to work.

**Comment by chelog** [comment]
All other methods work just fine, only the websocket one gives 403 error right after `connect()`ion. Should I go ping Pteroteam then?

**Comment by devnote-dev** [comment]
No, if you have access to Wings for the node you're using then set `allowed_origins` in "config.yml" to this:
```yml
allowed_origins:
  - "*"
```

Otherwise, contact your panel administrator about it.

**Comment by chelog** [comment]
Thanks! Didn't think that it works this way, I thought panel is acting like proxy in this case, 403 error is fixed now. However no output is forwarded to my `on` listener. However that's a story for another issue if I don't solve the problem myself. Thanks once more!
